In [ ]:
import numpy as np

In [5]:
#creating a 1D array
import numpy as np
arr=np.array([1,1,1,1])
print(arr)
print(arr.ndim)

[1 1 1 1]
1


In [19]:
#creating a 2D array
import numpy as np
arr=np.zeros((6,5))
print(arr)
print(arr.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


In [11]:
#fill the 2D array with zeros and ones
import numpy as np
arr=np.eye(2)
print(arr)
print(arr.ndim)

[[1. 0.]
 [0. 1.]]
2


In [23]:
#create a full function with 2D filler of 7
import numpy as np
arr=np.full((2,2),7)
print(arr)
print(arr.ndim)

[[7 7]
 [7 7]]
2


In [48]:
#using different slicing on array
import numpy as np
arr=np.eye(6)
print(arr[:,:])

print(arr[2:5,0:3])
print(arr[0:2,0:5])
print(arr[2:4,2:4])
print(arr[-3:-1,-3:-1])
print(arr[-4:-1,-4:-1])

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
#dimension of given array
import numpy as np
arr=np.eye(2)
print(arr)
print(arr.ndim)

[[1. 0.]
 [0. 1.]]
2


In [44]:
creating an 8D array
import numpy as np
arr=np.array([2,2,2,2],ndmin=8)
print(arr)


[[[[[[[[2 2 2 2]]]]]]]]
